services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ickoa
      POSTGRES_PASSWORD: ickoa
      POSTGRES_DB: ickoa
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
